### ISSUE TITLE
Add proper license

### ISSUE THREAD

**Issue by WilfHass** [UBC-MDS/chemboxR#26]
Work on this during thursday lab, after learning about licenses

**Comment by Suraporn** [comment]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly discussed.

**Comment by Suraporn** [comment]
Hello guys,

Let's discuss on the license of our package. It seems like there are several licenses that we can use, more information in this link [https://choosealicense.com/]. Since for our package, we do not intend to make any profit nor other people making profit from our work, therefore, I think the MIT license works fine for us. The MIT license is short and simple permissive license with conditions only requiring preservation of copyright and license notices. 

What do you think about our license? Any other ideas? 
@WilfHass @xFiveRivers @lukeyf

**Comment by WilfHass** [comment]
I think the MIT license is good for us, considering what we intend the package to be used for!

**Comment by lukeyf** [comment]
I would choose to use MIT since this is not for profit and we are creating this to help others.

**Comment by xFiveRivers** [comment]
Yeah the MIT should be enough for the scope of the project.

**Comment by Suraporn** [comment]
Ok, we are consensus to use the MIT license for our package.
